apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
  namespace: default
spec:
  storageClassName: normal
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/postgresql/data"
