apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kube-public
  name: traefik
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
